# Generated by Django 4.2 on 2024-07-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('contraseña', models.CharField(max_length=8)),
                ('numero_de_caso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datosdecontacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='ProgramarCita',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Yasoycliente',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.RenameField(
            model_name='programarcita',
            old_name='entregado',
            new_name='confirmar',
        ),
        migrations.RenameField(
            model_name='programarcita',
            old_name='fecha_de_entrega',
            new_name='fecha_de_cita',
        ),
    ]
